title = "Data visualisation Berlin"
invisibleSections = ["jobs"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "An open list to the data visualisation scene in Berlin. All people, things and places that are related to visualisation, infographic, data art, data journalism, research, and data tools are welcome!"
  keywords = "data visualisation visualisation design infographic information graphic data-driven journalism ddj interface design"
  author = "Jonas Parnow"
  twitter = "zeto"
  telegram = "visber"
  source = "https://github.com/Data-Visualization-Berlin/Datavis-Berlin-Website"
  imprint = "https://jonasparnow.com/imprint"
  privacy = "https://jonasparnow.com/privacy"
  direction = "ltr"

[languages]
  [languages.en]
    baseURL = "https://datavis.berlin"
    LanguageName = "English"
    languageCode = "en"
    weight = 1
    disableKinds = ["taxonomy", "section"]
  [languages.de]
    title = "Daten Visualisierung Berlin"
    baseURL = "https://de.datavis.berlin"
    description = "Eine offene List der Datenvisualisierungsszene in Berlin. Alle Menschen, Dinge und Orte, die mit Visualisierung, Infografik, Datenkunst, Datenjournalismus, Forschung und Datenanwendungen verwandt sind, sind willkommen!"
    keywords = "Visualisierung Daten Infografik Design Informationsgrafik Datenjournalismus DDJ Statistik Interfacedesign"
    LanguageName = "Deutsch"
    languageCode = "de"
    weight = 2
    disableKinds = ["taxonomy", "section"]
  [languages.it]
    baseURL = "https://it.datavis.berlin"
    title = "Data Visualisation Berlin"
    description = "Una lista aperta dedicata alla scena berlinese della data visualisation. Tutto ciò che riguarda persone, cose e luoghi che riguardano la visualizzazione dati, infografica, giornalismo con i dati, ricerca e data tools è benvenuto!"
    keywords = "data visualisation visualizzatione dati design infografiche information design grafica con i dati giornalismo con i dati interfacedesign data-driven journalism"
    LanguageName = "Italiano"
    languageCode = "it"
    weight = 2
    disableKinds = ["taxonomy", "section"]
  [languages.es]
    baseURL = "https://es.datavis.berlin"
    title = "Data Visualisation Berlin"
    description = "Una lista abierta de la escena de visualización de datos en Berlín. Toda las personas, cosas y lugares relacionados con la visualización, la infográfica, el data art, el periodismo de datos, la investigación y herramientas útiles son bienvenidos!"
    keywords = "diseño de visualización de datos infografía información gráfica periodismo de datos ddj interfacedesign"
    LanguageName = "Español"
    languageCode = "es"
    weight = 2
    disableKinds = ["taxonomy", "section"]
  [languages.fr]
    baseURL = "https://fr.datavis.berlin"
    title = "Datavisualisation à Berlin"
    description = "Une liste ouverte à propos de la scène Datavis à Berlin. Toutes les personnes, choses et endroits, qui sont reliés à la visualisation, à l'infographie, au data art, au journalisme de données, à la recherche et aux outils de données, sont les bienvenus !"
    keywords = "data visualisation visualisation design infographie information graphisme journalisme de données ddj design d'interface"
    LanguageName = "Français"
    languageCode = "fr"
    weight = 2
    disableKinds = ["taxonomy", "section"]
  [languages.tr]
    baseURL = "https://tr.datavis.berlin"
    title = "Data Visualisation Berlin"
    description = "eri Görselleştirmesi alanında Berlin’de olup bitene dair açık bir liste: Görselleştirmeyle, infografikle, veri bazlı sanatla, veri gazeteceliğiyle, araştırmayla ve yöntemlerle alâkalı herkese ve herşeye açıktır."
    keywords = "veri görselleştirmesi örselleştirme tasarım infografik bilgi tasarımı veri gazeteceliği ddj arayüz tasarımı"
    LanguageName = "Türkçe"
    languageCode = "tr"
    weight = 2
    disableKinds = ["taxonomy", "section"]
  [languages.ur]
    baseURL = "https://ur.datavis.berlin"
    title = "Data Visualisation Berlin"
    description = "An open list to the data visualisation scene in Berlin. All people, things and places that are related to visualisation, infographic, data art, data journalism, research, and data tools are welcome!"
    keywords = "data visualisation visualisation design infographic information graphic data-driven journalism ddj interface design"
    LanguageName = "اردو"
    languageCode = "ur"
    weight = 2
    disableKinds = ["taxonomy", "section"]
    direction = "rtl"
  [languages.ua]
    baseURL = "https://ua.datavis.berlin"
    title = "Data Visualisation Berlin"
    description = "An open list to the data visualisation scene in Berlin. All people, things and places that are related to visualisation, infographic, data art, data journalism, research, and data tools are welcome!"
    keywords = "data visualisation visualisation design infographic information graphic data-driven journalism ddj interface design"
    LanguageName = "Українська"
    languageCode = "ua"
    weight = 2
    disableKinds = ["taxonomy", "section"]
